@startuml Roof_Surface_Admin_manageFactory
skinparam Style strictuml
skinparam SequenceMessageAlignment center
actor Admin as admin
participant Web_Application as web_app
participant Fastapi as fastapi
participant MongoDB_factory as factory
participant MongoDB_building as building
participant MongoDB_history as history
participant MongoDB_image as image
participant MongoDB_defectlo as defect
admin -> web_app : 1.Open manage factory page
web_app -> fastapi : 2.HTTP GET /get_admin_manage_factory
fastapi -> factory : 3.Find all factory
factory --> fastapi : 4.Return list of all factory
fastapi --> web_app : 5.HTTP RESPONSE list of all factory
web_app --> admin : 6.Show factory
alt Remove factory
admin -> web_app : 7.Click remove button
web_app -> fastapi : 8.HTTP DELETE /factory/{factory_name_and_detail}
fastapi -> building : 9.Find building by factory id
fastapi -> history :10.Find history by building id
fastapi -> image : 11.Find image by history id
fastapi -> defect : 12.Find defect data by image id
fastapi -> defect : 13.Delete defect data
defect --> fastapi : 14.Delete defect data success
fastapi -> image : 15.Delete image data
image --> fastapi : 16.Delete image data success
fastapi -> history : 17.Delete history data
history --> fastapi : 18.Delete history data success 
fastapi -> building : 19.Delete building
building -> fastapi : 20.Delete building success
fastapi -> factory : 21.Delete factory 
factory -> fastapi : 22.Delete factory success
fastapi -> storage : 23.Delete path by factory path
fastapi --> web_app : 24.HTTP RESPONSE delete succeed
web_app -> fastapi : 25.HTTP GET /get_admin_manage_factory
fastapi -> factory : 26.Find all factory
factory --> fastapi : 27.Return list of all factory
fastapi --> web_app : 28.HTTP RESPONSE list of all factory
web_app --> admin : 29.Show factory
else Disable factory
admin -> web_app : 7.Click disable button
web_app -> fastapi : 8.HTTP PUT /put_change_facto_status
fastapi -> factory : 9.Change factory status
factory -> fastapi : 10.Return new factory status
fastapi --> web_app : 11.HTTP RESPONSE new factory status
web_app -> fastapi : 12.HTTP GET /get_admin_manage_factory
fastapi -> factory : 13.Find all factory
factory --> fastapi : 14.Return list of all factory
fastapi --> web_app : 15.HTTP Response list of all factory
web_app --> admin : 16.Show factory

end
@enduml