@startuml Roof_Surface_changePassword
skinparam Style strictuml
skinparam SequenceMessageAlignment center
actor User as user
participant Web_Application as web_app
participant Fastapi as fastapi
participant MongoDB_database as base
user -> web_app : Enter new password and click submit button
web_app -> fastapi : HTTP PUT /admin_change_password
fastapi -> base : Find user data
base --> fastapi : Return user data
fastapi -> fastapi : hash password
fastapi -> base : Update password
base --> fastapi : Return password changed
fastapi --> web_app : HTTP RESPONSE password changed
web_app --> user : Show password changed
@enduml