@startuml Roof_Surface_Admin_addPermission
skinparam Style strictuml
skinparam SequenceMessageAlignment center
actor Admin as admin
participant Web_Application as web_app
participant Fastapi as fastapi
participant MongoDB_database as base
admin -> web_app : 1.Click add button
web_app -> fastapi : 2.HTTP POST /post_permission
fastapi -> base : 3.Insert permission
base --> fastapi : 4.Return insert permission success
fastapi --> web_app :5.HTTP RESPONSE permission success
web_app -> fastapi : 6.HTTP GET /get_permission_factory
fastapi -> base : 7.Find permission by facory id
base --> fastapi : 8.Return permission
fastapi -> base : 9.Find user by user id\n in permission
base --> fastapi : 10.Return list of user
fastapi --> web_app : 11.HTTP RESPONSE list of user
web_app -> fastapi : 12.HTTP GET /get_not_permission_factory
fastapi -> base : 13.Find user don't have permssion
base --> fastapi : 14.Return list of user
fastapi --> web_app : 15.HTTP RESPONSE list of user
web_app --> admin : 16.Show list of user who have\n and don't have permission
@enduml