@startuml Roof_Surface_Admin_addAdmin
skinparam Style strictuml
skinparam SequenceMessageAlignment center
actor Admin as admin
participant Web_Application as web_app
participant Fastapi as fastapi
participant MongoDB_database as base
admin -> web_app : 1.Enter data and click submit
web_app -> fastapi : 2.HTTP POST /create_admin
fastapi -> base : 3.Find username
alt username not exists exists in database 
    base --> fastapi :4.Return username has not found
    fastapi -> base : 5.Insert admin data
    fastapi --> web_app : 6.HTTP RESPONSE create admin success
    web_app --> admin : 7.ceata admin succeeded
else username already in database
    base --> fastapi : 4.Return user has found
    fastapi --> web_app : 5.HTTP RESPONSE sign up fail
    web_app --> admin : 6.Show this username already used
end
@enduml