@startuml Roof_Surface_changePassword
skinparam Style strictuml
skinparam SequenceMessageAlignment center
actor User as user
participant Web_Application as web_app
participant Fastapi as fastapi
participant MongoDB_user as userdb
user -> web_app : 1.Enter new password and click submit button
web_app -> fastapi : 2.HTTP PUT /admin_change_password
fastapi -> userdb : 3.Find user data
userdb --> fastapi : 4.Return user data
fastapi -> fastapi : 5.Hash password
fastapi -> userdb : 6.Update password
userdb --> fastapi : 7.Return password changed
fastapi --> web_app : 8.HTTP RESPONSE password changed
web_app --> user : 9.Show password changed
@enduml