@startuml Roof_Surface_changePassword
skinparam Style strictuml
skinparam SequenceMessageAlignment center
actor User as user
participant Web_Application as web_app
participant Fastapi as fastapi
participant MongoDB_user as userdb
user -> web_app : 1.Enter to profile page
user -> web_app : 2.Enter old password and new password \n and click enter button
web_app -> fastapi : 3.HTTP PUT /put_change_password
fastapi -> userdb : 4.Find user data
userdb --> fastapi : 5.Return user data
fastapi -> fastapi : 6.check verify old password
alt Old password correct
fastapi -> fastapi : 7.hash password
fastapi -> userdb : 8.Update password
userdb --> fastapi : 9.Return password changed
fastapi --> web_app : 10.HTTP RESPONSE password changed
web_app --> user : 11.Show password changed
else Old password incorrect
fastapi --> web_app : 7.HTTP RESPONSE 400 old password is incorrect
end
@enduml