@startuml Roof_Surface_deleteBuilding
skinparam Style strictuml
skinparam SequenceMessageAlignment center
actor User as user
participant Web_Application as web_app
participant Fastapi as fastapi
participant MongoDB_permission as permission
participant MongoDB_building as building
participant MongoDB_history as history
participant MongoDB_image as image
participant MongoDB_defectlo as defect
user -> web_app : 1.Click delete building button
web_app -> fastapi : 2.HTTP DELETE /building/{building_id}
fastapi -> building : 3.Delete Building
building --> fastapi : 4.Return delete building success 
fastapi -> history : 5.Delete history
history --> fastapi : 6.Return delete history success
fastapi -> image : 7.Delete image
image --> fastapi : 8.Return delete image success
fastapi -> defect : 9.Delete defect in image
defect --> fastapi : 10.Return delete defect success
fastapi --> web_app : 11.HTTP RESPONSE delete builind success
web_app -> fastapi : 12.HTTP GET /get_user_factory
fastapi -> permission : 13.Find factory which\n user have permission 
permission --> fastapi : 14.Return fatory data
fastapi -> building : 15.Find building in factory
building --> fastapi : 16.Return building name and id
fastapi --> web_app : 17.HTTP RESPONSE factory \nand building data
web_app --> user : 18.Show list of factory and builing
@enduml