@startuml Roof_Surface_viewHistory
skinparam Style strictuml
skinparam SequenceMessageAlignment center
actor User as user
participant Web_Application as web_app
participant Fastapi as fastapi
participant MongoDB_image as image
participant MongoDB_defectlo as defect
participant Storage as storage
user -> web_app : 1.Click view button
web_app -> fastapi : 2.HTTP GET /get_image
fastapi -> image : 3.Get image data
image --> fastapi : 4.Return image data
fastapi -> defect : 5.Get defect data by image id
defect --> fastapi : 6.Return defect data
fastapi --> web_app : 7.HTTP RESPONSE image with defect data
web_app -> storage : 8.Get image by image path
web_app --> user : 9.Show all image with defect data
@enduml